### PR TITLE
Fix picket-fence frequency mislabelling in PSRFITS output

### LINKED ISSUE #27: VCSbeam Frequency Channel and Frequency Mismatch
This is regarding the testing of coarse channel pairs in the context of Project D0036 using MWAX data. Taking the example of channels ch153-154, it has been observed that the low/high channels do not match the actual frequency values. Additionally, there seems to be an issue with the numerical value of the center frequency.
截图 2023-07-10 15-29-21

### PR DESCRIPTION
**Pull request by bwmeyers**
Resolves #27 

I believe this fixes the problem of incorrect frequency labels in the subint DAT_FREQ tables and does not change the behaviour of contiguous-band VCSBeam processing.

### CODE REVIEW

**Comment by bwmeyers** [comment]
I am currently getting a couple of folks to do some tests before signing off on this, at which point I'll also remove all of the debugging extras I included before actually merging.

File: src/beam_psrfits.c [hunk 1]
```diff
@@ -145,12 +156,21 @@ void populate_spliced_psrfits_header(
...
-        iC = i / vm->nfine_chan + first_coarse_chan_idx;
+        /* BWM comment, 20 Oct 2023:
+         * Previously, the addition of the `first_coarse_chan_index` to `iC` caused an offset
+         * proportional to that coarse channel number (multiplied by the fine channel width).
+         * This is fine when it is a contiguous band because that index is always zero! But in
+         * picket-fence mode, because the starting frequency is already defined via "first
+         * coarse channel" number, we are only ever concerned with the fine channel additions
+         * in this loop.
+         */
+        iC = i / vm->nfine_chan;
```
Comment (chiamintan) [inline src/beam_psrfits.c:171]: So this is the main thing to change to get it work right? Everything elsewhere seems like all stylistic changes

**Review by chiamintan — APPROVED** [review]

File: src/beam_psrfits.c (hunk 1 above)
Comment (bwmeyers) [reply src/beam_psrfits.c:171]: Yes, this was the primary culprit I believe.
